project:
  type: website

website:
  title: "sum title"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [minty, styles.scss]
    toc: true
