project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: recherche.qmd
        text: Projets de recherche
        icon: "lightning-charge-fill"
      - href: dev.qmd
        text: Projets R
        icon: "terminal-fill"
      - href: publi.qmd
        text: Publications
        icon: "pen-fill"
    tools:
      - icon: github
        href: https://github.com/dagousket
      - icon: linkedin
        href: https://www.linkedin.com/in/swann-floc-hlay-924674225/
      - icon: mortarboard
        href: https://orcid.org/0000-0003-1477-830X
      - icon: envelope
        href: mailto:swann.flochlay+gitpage@gmail.com
    search: false

format:
  html:
    theme: [minty, styles.scss]
    toc: true
    from: markdown+emoji
    cap-location: margin

bibliography: refs.bib
